### ISSUE TITLE
Installation error on macOS 10.13.6

### ISSUE THREAD

**Issue by Si-Lynnn** [arpit15/tiny-differentiable-simulator#1]
When compiling the TDS, an error about \<filesystem\> happened. This same error also happened when I directly install python version.
```
[  6%] Built target rbdl-static
[  7%] Built target tinyxml2
[ 18%] Built target opengl_window
[ 19%] Built target cpp_base64
[ 22%] Built target dear_imgui
[ 23%] Built target crossguid
[ 78%] Built target zmq
[ 79%] Built target gtest
[ 80%] Built target gtestmain
[ 80%] Building CXX object test/CMakeFiles/test_rbdl_tds.dir/test_rbdl.cpp.o
In file included from /Users/ZilinSi/Downloads/tiny-differentiable-simulator/test/test_rbdl.cpp:3:
In file included from /Users/ZilinSi/Downloads/tiny-differentiable-simulator/test/./rbdl_test_utils.hpp:25:
In file included from /Users/ZilinSi/Downloads/tiny-differentiable-simulator/test/../src/utils/file_utils.hpp:3:
/Users/ZilinSi/Downloads/tiny-differentiable-simulator/test/../src/utils/filesystem.hpp:50:9: error: 
      Could not find system header "<filesystem>" or "<experimental/filesystem>"
#       error Could not find system header "<filesystem>" or "<experimental/filesystem>"
        ^
/Users/ZilinSi/Downloads/tiny-differentiable-simulator/test/../src/utils/filesystem.hpp:66:17: fatal error: 
      'filesystem' file not found
#       include <filesystem>
                ^~~~~~~~~~~~
2 errors generated.
```
Have tried the methods in: https://stackoverflow.com/questions/42633477/macos-clang-c17-filesystem-header-not-found.
1) set c++ flag libc++
2) upgrade the llvm
But neither solved the problem

xcode version: 10.1
clang version: 11.1.0

**Comment by arpit15** [comment]
For old xcode, the filesystem might be located at other locations like `/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/filesystem`. If you find the location, then include this instead of `<filesystem>`  on [this](https://github.com/arpit15/tiny-differentiable-simulator/blob/master/src/utils/filesystem.hpp#L66) line

**Comment by Si-Lynnn** [comment]
Thanks Arpit! So I looked into the directory you mentioned but there was no filesystem.
Instead, I upgraded the system to 10.15, xcode to 12.4 and clang to 12.0.0, and now it works well :)
